# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: keyexchange.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'keyexchange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11keyexchange.proto\x12\"Proregia.Bluetooth.Contracts.Proto\"\xdd\x01\n\x07Metrics\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0f\n\x07os_type\x18\x03 \x01(\t\x12\x12\n\nos_version\x18\x04 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x05 \x01(\t\x12\x15\n\rdevice_serial\x18\x06 \x01(\t\x12\x18\n\x10\x61pplication_name\x18\x07 \x01(\t\x12\x1b\n\x13\x61pplication_package\x18\x08 \x01(\t\x12\x17\n\x0flibrary_version\x18\t \x01(\t\x12\x0f\n\x07xamarin\x18\n \x01(\x08\"w\n\x10\x44\x65viceIdentifier\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x12\n\nbt_address\x18\x02 \x01(\t\x12<\n\x07metrics\x18\x03 \x01(\x0b\x32+.Proregia.Bluetooth.Contracts.Proto.Metrics\"#\n\x0bServerNonce\x12\x14\n\x0cserver_nonce\x18\x01 \x01(\t\"\xdc\x01\n\x11\x45ncryptKeyRequest\x12\x11\n\tchallenge\x18\x01 \x01(\t\x12\x17\n\x0fpump_public_key\x18\x02 \x01(\t\x12\x16\n\x0e\x61pp_public_key\x18\x03 \x01(\t\x12\x12\n\nbt_address\x18\x04 \x01(\t\x12\"\n\x1amessage_attestation_object\x18\x05 \x01(\t\x12\r\n\x05nonce\x18\x06 \x01(\t\x12<\n\x07metrics\x18\x07 \x01(\x0b\x32+.Proregia.Bluetooth.Contracts.Proto.Metrics\"-\n\x12\x45ncryptKeyResponse\x12\x17\n\x0f\x65ncrypted_bytes\x18\x01 \x01(\t2}\n\x0cNonceRequest\x12m\n\x04Send\x12\x34.Proregia.Bluetooth.Contracts.Proto.DeviceIdentifier\x1a/.Proregia.Bluetooth.Contracts.Proto.ServerNonce2\x83\x01\n\nEncryptKey\x12u\n\x04Send\x12\x35.Proregia.Bluetooth.Contracts.Proto.EncryptKeyRequest\x1a\x36.Proregia.Bluetooth.Contracts.Proto.EncryptKeyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyexchange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICS']._serialized_start=58
  _globals['_METRICS']._serialized_end=279
  _globals['_DEVICEIDENTIFIER']._serialized_start=281
  _globals['_DEVICEIDENTIFIER']._serialized_end=400
  _globals['_SERVERNONCE']._serialized_start=402
  _globals['_SERVERNONCE']._serialized_end=437
  _globals['_ENCRYPTKEYREQUEST']._serialized_start=440
  _globals['_ENCRYPTKEYREQUEST']._serialized_end=660
  _globals['_ENCRYPTKEYRESPONSE']._serialized_start=662
  _globals['_ENCRYPTKEYRESPONSE']._serialized_end=707
  _globals['_NONCEREQUEST']._serialized_start=709
  _globals['_NONCEREQUEST']._serialized_end=834
  _globals['_ENCRYPTKEY']._serialized_start=837
  _globals['_ENCRYPTKEY']._serialized_end=968
# @@protoc_insertion_point(module_scope)
